// js/quotes-data.js

const dailyQuotes = [
  { author: "Pablo Picasso", quote_en: "Every child is an artist. The problem is how to remain an artist once he grows up.", quote_hu: "Minden gyerek művész. A probléma az, hogyan maradjon művész, miután felnő." },
  { author: "Vincent van Gogh", quote_en: "I dream my painting, and then I paint my dream.", quote_hu: "Megálmodom a festményemet, és aztán megfestem az álmomat." },
  { author: "Leonardo da Vinci", quote_en: "Painting is poetry that is seen rather than felt, and poetry is painting that is felt rather than seen.", quote_hu: "A festészet költészet, amit látnak, nem pedig éreznek, a költészet pedig festészet, amit éreznek, nem pedig látnak." },
  { author: "Andy Warhol", quote_en: "Don't think about making art, just get it done. Let everyone else decide if it's good or bad, whether they love it or hate it.", quote_hu: "Ne gondolkozz a művészetalkotáson, csak csináld meg. Hagyd, hogy mindenki más eldöntse, jó-e vagy rossz, szeretik-e vagy utálják." },
  { author: "Claude Monet", quote_en: "Color is my day-long obsession, joy and torment.", quote_hu: "A szín az én egész napos megszállottságom, örömöm és gyötrelmem." },
  { author: "Georgia O'Keeffe", quote_en: "I found I could say things with color and shapes that I couldn't say any other way – things I had no words for.", quote_hu: "Rájöttem, hogy színekkel és formákkal olyan dolgokat tudok mondani, amiket semmilyen más módon nem – dolgokat, amikre nem voltak szavaim." },
  { author: "Michelangelo", quote_en: "The greater the artist, the greater the doubt. Perfect confidence is granted to the less talented as a consolation prize.", quote_hu: "Minél nagyobb a művész, annál nagyobb a kétség. A tökéletes magabiztosság a kevésbé tehetségeseknek adatik vigaszdíjként." },
  { author: "Salvador Dalí", quote_en: "Have no fear of perfection - you'll never reach it.", quote_hu: "Ne félj a tökéletességtől – soha nem fogod elérni." },
  { author: "Frida Kahlo", quote_en: "I paint my own reality.", quote_hu: "A saját valóságomat festem." },
  { author: "Henri Matisse", quote_en: "Creativity takes courage.", quote_hu: "A kreativitáshoz bátorság kell." },
  { author: "Banksy", quote_en: "Art should comfort the disturbed and disturb the comfortable.", quote_hu: "A művészetnek meg kell vigasztalnia a háborgókat, és fel kell háborítania a kényelmeseket." },
  { author: "Edgar Degas", quote_en: "Art is not what you see, but what you make others see.", quote_hu: "A művészet nem az, amit te látsz, hanem amit másokkal láttatsz." },
  { author: "Wassily Kandinsky", quote_en: "Color is a power which directly influences the soul.", quote_hu: "A szín egy erő, amely közvetlenül befolyásolja a lelket." },
  { author: "Paul Cézanne", quote_en: "A work of art which did not begin in emotion is not art.", quote_hu: "Egy műalkotás, amely nem érzelemben kezdődött, nem művészet." },
  { author: "Rembrandt", quote_en: "Painting is the grandchild of nature. It is related to God.", quote_hu: "A festészet a természet unokája. Rokonságban áll Istennel." },
  { author: "Jackson Pollock", quote_en: "The painting has a life of its own. I try to let it come through.", quote_hu: "A festménynek saját élete van. Én csak megpróbálom hagyni, hogy ez átjöjjön." },
  { author: "Ansel Adams", quote_en: "You don't take a photograph, you make it.", quote_hu: "Nem készítesz egy fényképet, hanem megalkotod azt." },
  { author: "Frank Lloyd Wright", quote_en: "Art is a discovery and development of elementary principles of nature into beautiful forms suitable for human use.", quote_hu: "A művészet a természet elemi elveinek felfedezése és fejlesztése az emberi használatra alkalmas gyönyörű formákká." },
  { author: "Yayoi Kusama", quote_en: "My art originates from hallucinations only I can see.", quote_hu: "Művészetem olyan hallucinációkból ered, amiket csak én látok." },
  { author: "Marcel Duchamp", quote_en: "I don't believe in art. I believe in artists.", quote_hu: "Nem hiszek a művészetben. Hiszek a művészekben." },
  { author: "Auguste Rodin", quote_en: "The main thing is to be moved, to love, to hope, to tremble, to live.", quote_hu: "A lényeg, hogy megindulj, szeress, remélj, reszkess, élj." },
  { author: "Gustav Klimt", quote_en: "All art is erotic.", quote_hu: "Minden művészet erotikus." },
  { author: "Piet Mondrian", quote_en: "The purest and most thoughtful minds are those which love colour the most.", quote_hu: "A legtisztább és leggondolkodóbb elmék azok, amelyek a legjobban szeretik a színeket." },
  { author: "Mark Rothko", quote_en: "A painting is not a picture of an experience, but is the experience.", quote_hu: "Egy festmény nem egy élmény képe, hanem maga az élmény." },
  { author: "Joan Miró", quote_en: "I try to apply colors like words that shape poems, like notes that shape music.", quote_hu: "Megpróbálom a színeket úgy alkalmazni, mint a szavakat, amelyek verseket formálnak, vagy a hangokat, amelyek zenét alkotnak." },
  { author: "Francis Bacon", quote_en: "The job of the artist is always to deepen the mystery.", quote_hu: "A művész feladata mindig a rejtély elmélyítése." },
  { author: "Edward Hopper", quote_en: "If I could say it in words there would be no reason to paint.", quote_hu: "Ha szavakkal is el tudnám mondani, nem lenne okom festeni." },
  { author: "René Magritte", quote_en: "Art evokes the mystery without which the world would not exist.", quote_hu: "A művészet azt a rejtélyt idézi fel, amely nélkül a világ nem létezne." },
  { author: "David Hockney", quote_en: "The world is in color, you have to be very naïve to think only in black and white.", quote_hu: "A világ színes, nagyon naivnak kell lenned ahhoz, hogy csak fekete-fehérben gondolkodj." },
  { author: "Jean-Michel Basquiat", quote_en: "I don't listen to what art critics say. I don't know anybody who needs a critic to find out what art is.", quote_hu: "Nem hallgatok arra, amit a műkritikusok mondanak. Nem ismerek senkit, akinek kritikusra lenne szüksége ahhoz, hogy megtudja, mi a művészet." },
  // ... és még sok-sok idézet ... (A teljes lista 105 idézetet tartalmaz a teljesség igénye nélkül)
];