[build]
  command = "npx -y pagefind --site ./"
  publish = "."

[functions]
  directory = "netlify/functions/"

[build.processing]
  skip_processing = false
  [build.processing.html]
    pretty_urls = false
  [build.processing.images]
    compress = true