[build]
  command = "echo 'No build command'"
  publish = "."

[functions]
  directory = "netlify/functions/"
  # --- EZ AZ ÚJ RÉSZ, AMI KIKAPCSOLJA A PROBLÉMÁS OPTIMALIZÁLÁST ---
[build.processing]
  [build.processing.html]
    pretty_urls = false