[build]
  command = "npx -y pagefind --site ./"
  publish = "."

[functions]
  directory = "netlify/functions/"

[build.processing]
  skip_processing = false
  [build.processing.html]
    pretty_urls = false
  [build.processing.images]
    compress = true
    # Netlify CMS biztonsági szabályainak kiegészítése
# Netlify CMS biztonsági szabályainak kiegészítése (VÉGLEGES)
[[headers]]
  for = "/admin/*"
  [headers.values]
    Content-Security-Policy = "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://gc.zgo.at https://cdnjs.cloudflare.com https://www.googletagmanager.com https://cusdis.com https://www.free-counters.org https://identity.netlify.com https://unpkg.com; connect-src 'self' https://*.goatcounter.com https://*.google-analytics.com https://cusdis.com wss://cusdis.com; img-src 'self' data: https:; frame-src 'self' https://cusdis.com;"