# Netlify Sitemap Plugin beállítása
[[plugins]]
package = "netlify-plugin-sitemap"

  [plugins.inputs]
  # Itt adhatjuk meg, hogy mely oldalakat NE tegye bele a sitemap-be.
  # Az admin felületet felesleges indexelni.
  exclude = [
    "/admin/**"
  ]